services:

  openvpn:
    image: kylemanna/openvpn:2.4

    env_file: "${SERVICE_ROOT}/.env"

    environment:
      PUID: 1000
      GUID: 1000

    ports:
      - 1194:1194/udp

    ## Base homelab config
    volumes:
      - ${SERVICE_ROOT}/storage/data:/etc/openvpn:rw

    ## Base homelab config
    hostname: ${SERVICE_HOSTNAME}
    container_name: ${SERVICE_NAME}
    restart: unless-stopped

    networks:
      - default
      - ${HOMELAB_NETWORK}
    
    cap_add:
      - NET_ADMIN

networks:
  default:
   name: ${SERVICE_NETWORK}
  homelab_network_proxy:
   name: ${HOMELAB_NETWORK}
   external: true

