services:

  pygallery:
    image: bpatrik/pigallery2:latest

    env_file: "${SERVICE_ROOT}/.env"

    environment:
      PUID: 1000
      GUID: 1000
      NODE_ENV: production

    # ports:
    #   - 80:80

    ## Base homelab config
    volumes:
      - db-data:/app/data/db
      - ${SERVICE_ROOT}/storage/tmp:/app/data/tmp
      - ${SERVICE_ROOT}/storage/config:/app/data/config
      - ${SERVICE_ROOT}/storage/pictures:/app/data/images:ro

    ## Base homelab config
    hostname: ${SERVICE_HOSTNAME}
    container_name: ${SERVICE_NAME}
    restart: unless-stopped

    networks:
      - default
      - ${HOMELAB_NETWORK}

volumes:
    db-data:

networks:
  default:
   name: ${SERVICE_NETWORK}
  homelab_network_proxy:
   name: ${HOMELAB_NETWORK}
   external: true

