services:

  npm:
    image: jc21/nginx-proxy-manager:2.10.4

    env_file: "${SERVICE_ROOT}/.env"

    environment:
      PUID: 1000
      GUID: 1000

    ports:
      - 80:80
      - 443:443
      - 81:81

    ## Base homelab config
    volumes:
      - ${SERVICE_ROOT}/storage/data:/data
      - ${SERVICE_ROOT}/storage/letsencrypt:/etc/letsencrypt 

    ## Base homelab config
    hostname: ${SERVICE_HOSTNAME}
    container_name: ${SERVICE_NAME}
    restart: unless-stopped

networks:
  default:
   name: ${SERVICE_NETWORK}
  homelab_network_proxy:
   name: ${HOMELAB_NETWORK}
   external: true
