services:

  heimdall:
    image: lscr.io/linuxserver/heimdall:latest

    env_file: "${SERVICE_ROOT}/.env"

    environment:
      PUID: 1000
      GUID: 1000
      TZ: Europe/Paris

    # ports:
    #   - 80:80

    ## Base homelab config
    volumes:
      - ${SERVICE_ROOT}/storage/config:/config

    ## Base homelab config
    hostname: ${SERVICE_HOSTNAME}
    container_name: ${SERVICE_NAME}
    restart: unless-stopped

    networks:
      - default
      - ${HOMELAB_NETWORK}

networks:
  default:
   name: ${SERVICE_NETWORK}
  homelab_network_proxy:
   name: ${HOMELAB_NETWORK}
   external: true

