services:

  beszel:
    image: henrygd/beszel:latest

    env_file: "${SERVICE_ROOT}/.env"

    environment:
      PUID: 1000
      GUID: 1000

    # ports:
    #   - 80:80

    ## Base homelab config
    volumes:
      - ${SERVICE_ROOT}/storage/data:/beszel_data

    ## Base homelab config
    hostname: ${SERVICE_HOSTNAME}
    container_name: ${SERVICE_NAME}
    restart: unless-stopped

    networks:
      - default
      - ${HOMELAB_NETWORK}

  beszel-agent:
    image: henrygd/beszel-agent:latest

    env_file: "${SERVICE_ROOT}/.env"
        
    environment:
      PUID: 1000
      GUID: 1000
      PORT: ${SERVICE_AGENT_PORT}
      KEY: ${SERVICE_AGENT_KEY}
      
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
        
    hostname: ${SERVICE_AGENT_HOSTNAME}
    container_name: ${SERVICE_AGENT_NAME}
    restart: unless-stopped

    networks:
      - default
      - ${HOMELAB_NETWORK}

networks:
  default:
   name: ${SERVICE_NETWORK}
  homelab_network_proxy:
   name: ${HOMELAB_NETWORK}
   external: true

